<a href="https://colab.research.google.com/github/Shreyasinha518/FSP-CSE/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello")

Hello


In [2]:
import numpy as np
a=np.arange(12)
print(a)
print("Last element : ",a[-1])
print("Dimension of a : ",a.ndim)
print("Shape of a : ",a.shape)
print("Data type of each element : ",a.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Last element :  11
Dimension of a :  1
Shape of a :  (12,)
Data type of each element :  int64


In [3]:
print(a)
print("##############")
b=a.reshape(3,4)
print(b)
print("Dimension of b : ",b.ndim)
print("Sum of all the elements : ",b.sum())
print("Average of all the elements : ",b.mean())
print("Row sum : ",b.sum(axis=1))
print("Column sum : ",b.sum(axis=0))


[ 0  1  2  3  4  5  6  7  8  9 10 11]
##############
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Dimension of b :  2
Sum of all the elements :  66
Average of all the elements :  5.5
Row sum :  [ 6 22 38]
Column sum :  [12 15 18 21]


In [4]:
print(b)
print("#############################")
print(b.T)
print("#############################")
print(np.ravel(b))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
#############################
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
#############################
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [5]:
m=np.array([[1,2],[3,4]])
print(m)
c=m*3
print(c)
print(m>3)

[[1 2]
 [3 4]]
[[ 3  6]
 [ 9 12]]
[[False False]
 [False  True]]


In [6]:
print(m)
print("########################")
n=np.array([[5,6],[7,8]])
print(n)
print("########################")
print(m*n)
print("########################")
print(m.dot(n))

[[1 2]
 [3 4]]
########################
[[5 6]
 [7 8]]
########################
[[ 5 12]
 [21 32]]
########################
[[19 22]
 [43 50]]


In [7]:
np.sqrt(289)

np.float64(17.0)

In [8]:
k1=np.zeros((3,4))
print(k1)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
import pandas as pd
s1=pd.Series([11,22,33,44])
print(s1)
s2=pd.Series([11,22,33,44], index=['a','b','c','d'])
print(s2)

0    11
1    22
2    33
3    44
dtype: int64
a    11
b    22
c    33
d    44
dtype: int64


In [12]:
d1={"id":120,"name":"Shreya","age":20}
s3=pd.Series(d1)
print(s3)

id         120
name    Shreya
age         20
dtype: object


In [13]:
d2={
    "names":["raj","avik","vipin","kamal"],
    "phy":[89,87,97,86],
    "chem":[88,87,89,86]
}
df=pd.DataFrame(d2)
print(df)

   names  phy  chem
0    raj   89    88
1   avik   87    87
2  vipin   97    89
3  kamal   86    86
